// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvEZrE8KiBmFq8xdtOQyTnTpfuKpIcuE',
    appId: '1:1009598448782:web:b718763160f9e178d3b5df',
    messagingSenderId: '1009598448782',
    projectId: 'silag-30cc3',
    authDomain: 'silag-30cc3.firebaseapp.com',
    storageBucket: 'silag-30cc3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8m_16_n1eap8CDC3I3aIJTnks7gh_r4',
    appId: '1:1009598448782:android:ab6f41740aee4e06d3b5df',
    messagingSenderId: '1009598448782',
    projectId: 'silag-30cc3',
    storageBucket: 'silag-30cc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdh5YT_-JjLvHDpsYM5lGO3ROhpDnBWg',
    appId: '1:1009598448782:ios:f725e62959fcf808d3b5df',
    messagingSenderId: '1009598448782',
    projectId: 'silag-30cc3',
    storageBucket: 'silag-30cc3.firebasestorage.app',
    iosBundleId: 'com.example.silag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZdh5YT_-JjLvHDpsYM5lGO3ROhpDnBWg',
    appId: '1:1009598448782:ios:f725e62959fcf808d3b5df',
    messagingSenderId: '1009598448782',
    projectId: 'silag-30cc3',
    storageBucket: 'silag-30cc3.firebasestorage.app',
    iosBundleId: 'com.example.silag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBvEZrE8KiBmFq8xdtOQyTnTpfuKpIcuE',
    appId: '1:1009598448782:web:270ba1361957a9b1d3b5df',
    messagingSenderId: '1009598448782',
    projectId: 'silag-30cc3',
    authDomain: 'silag-30cc3.firebaseapp.com',
    storageBucket: 'silag-30cc3.firebasestorage.app',
  );
}
